name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release.apk

      - name: Download manifest artifact
        uses: actions/download-artifact@v4
        with:
          name: manifest.json

      - name: Download app icon artifact
        uses: actions/download-artifact@v4
        with:
          name: karoo-reminder.png

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          generateReleaseNotes: true
          artifacts: app-release.apk, manifest.json, karoo-reminder.png

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}